### ISSUE TITLE
resources/resource-list.md should be a section of README.MD

### ISSUE THREAD

**Issue by codingwithchad** [OperationCode/on-belay#13]
The section would be better on the README.MD and removed from a subdirectory.
'''
Resources for this project

Python - http://docs.python-guide.org/en/latest/

We're using version 3.6.2 (which is the latest version of Python). You can download it from https://www.python.org/downloads/release/python-362/

Trello

We're using Trello to track the project goals. https://trello.com/invite/onbelay1/209f7fb3a14b4619ae410dbc5ec56838
'''

**Comment by AshTemp** [comment]
I'd actually like to see it added to the contributor's guide, it seems like the best place for all that information so that people don't have to go hunting it down.
