### ISSUE TITLE
Create Fake Data for Testing

### ISSUE THREAD

**Issue by aaron-junot** [OperationCode/on-belay#30]
There are certain components that depend on data existing. We would like to test these components before we start collecting actual data. An example is the graph on the landing page. We will need at least a month's worth of fake mood data.

We need a fake data set that can be loaded into the database. The format for the data may depend on which DB we go with (I think SQLite is on the table). However, I'm pretty sure all of our options will work with CSV, so that might be a good start.

**Comment by apex-omontgomery** [comment]
https://github.com/OperationCode/on-belay/pull/31
